### ISSUE TITLE
Tests are boilerplated with unnecessary declarations

### ISSUE THREAD

**Issue by gabriel-card** [globocom/azkaban-cli#16]
Some tests have declarations that are unnecessary to be declared, like:
```
def tearDown(self):
    pass
```

**Comment by hermancaldara** [comment]
I'm on it!

**Comment by joaofix** [comment]
PR #43 fixes this issue

**Comment by dmvieira** [comment]
Thank you @hermancaldara and @marceloFA ! Done by #41
