### ISSUE TITLE
Add Fetch Flows of a Project API call

### ISSUE THREAD

**Issue by aguimaraesduarte** [globocom/azkaban-cli#20]
Add the corresponding API call, as [documented in the Azkaban project](https://azkaban.github.io/azkaban/docs/latest/#api-fetch-flows-of-a-project)

`Given a project name, this API call fetches all flow ids of that project.`

**Comment by Perkles** [comment]
Hi @aguimaraesduarte can I work in this issue?

**Comment by aguimaraesduarte** [comment]
> Hi @aguimaraesduarte can I work in this issue?

Of course @Perkles Go ahead!

**Comment by aguimaraesduarte** [comment]
@Perkles It seems like this is actually already implemented in the code base :o
I'll be closing this issue, but feel free to contribute in any of the other open ones (lots of other API calls missing). Sorry for the confusion!
