### ISSUE TITLE
Add Fetch Execution Job Logs API call

### ISSUE THREAD

**Issue by aguimaraesduarte** [globocom/azkaban-cli#22]
Add the corresponding API call, as [documented in the Azkaban project](https://azkaban.github.io/azkaban/docs/latest/#api-fetch-execution-job-logs)

`Given an execution id and a job id, this API call fetches the correponding job logs. The log text can be quite large sometimes, so this API call also expects the parameters offset and length to be specified.`

**Comment by Perkles** [comment]
@aguimaraesduarte can i ?

**Comment by aguimaraesduarte** [comment]
@Perkles Yes!
