### ISSUE TITLE
Add Fetch Flow Execution Updates API call

### ISSUE THREAD

**Issue by aguimaraesduarte** [globocom/azkaban-cli#23]
Add the corresponding API call, as [documented in the Azkaban project](https://azkaban.github.io/azkaban/docs/latest/#api-fetch-flow-execution-updates)

`This API call fetches the updated information for an execution. It filters by lastUpdateTime which only returns job information updated afterwards.`

**Comment by Perkles** [comment]
Can i take this one ?

**Comment by aguimaraesduarte** [comment]
@Perkles Yes!
