### ISSUE TITLE
Add Fetch Executions of a Flow API call

### ISSUE THREAD

**Issue by sbouchardet** [globocom/azkaban-cli#25]
Add the **Fetch Executions of a Flow** API call, as [documented in the Azkaban project](https://azkaban.readthedocs.io/en/latest/ajaxApi.html)

`Given a project name, and a certain flow, this API call provides a list of corresponding executions.`

**Comment by jessescn** [comment]
Hey, can i pick this one?

**Comment by LeonardoFurtado** [comment]
I will try it

**Comment by rrrahal** [comment]
Hey, i think i was able to do this, can you guys check #54?
