### ISSUE TITLE
Add Fetch Running Executions of a Flow API call

### ISSUE THREAD

**Issue by sbouchardet** [globocom/azkaban-cli#28]
Add the **Fetch Running Executions of a Flow** API call, as [documented in the Azkaban project](https://azkaban.readthedocs.io/en/latest/ajaxApi.html)

`Given a project name and a flow id, this API call fetches only executions that are currently running.`

**Comment by jessescn** [comment]
Hey, can this one?

**Comment by rrrahal** [comment]
can i?

**Comment by dmvieira** [comment]
Off course! If you need some help please contact us

**Comment by joaovictortr** [comment]
May I take on this issue? What is the best way to contact the maintainers if I need any assistance?

**Comment by jackson541** [comment]
Hello @aguimaraesduarte , has this issue been solved?

**Comment by aguimaraesduarte** [comment]
> Hello @aguimaraesduarte , has this issue been solved?

Hi @jackson541 it seems it has already been done. I will close the PR. Sorry for the inconvenience.
