### ISSUE TITLE
Add Cancel a Flow Execution API call

### ISSUE THREAD

**Issue by sbouchardet** [globocom/azkaban-cli#29]
Add the **Cancel a Flow Execution** API call, as [documented in the Azkaban project](https://azkaban.readthedocs.io/en/latest/ajaxApi.html)

`Given an execution id, this API call cancels a running flow. If the flow is not running, it will return an error message.`

**Comment by jessescn** [comment]
If this issue is not yet resolved, can i get it? :)

**Comment by sbouchardet** [comment]
Sure! go for it =)
