### ISSUE TITLE
Add Fetch Jobs of a Flow API call

### ISSUE THREAD

**Issue by sbouchardet** [globocom/azkaban-cli#31]
Add the **Fetch Jobs of a Flow** API call, as [documented in the Azkaban project](https://azkaban.readthedocs.io/en/latest/ajaxApi.html)

`For a given project and a flow id, this API call fetches all the jobs that belong to this flow. It also returns the corresponding graph structure of those jobs.`

**Comment by aguimaraesduarte** [comment]
On it
