### ISSUE TITLE
 Create requirements-test and remove test libs from requirements

### ISSUE THREAD

**Issue by ggalves** [globocom/azkaban-cli#33]
The project only contains the `requirements.txt` file for all app and test requirements.

They should be separated into two different files, avoiding unnecessary installation of libraries (like `responses`).

**Comment by pniedzwiedzinski** [comment]
I would like to do this

**Comment by dmvieira** [comment]
Welcome aboard @pniedzwiedzinski ! Do you need some help to understand?

**Comment by lioman** [comment]
Perhaps you want to use a Pipfile instead of requirements.txt. There you have the separation between development and general libraries.
