### ISSUE TITLE
Fix function docstrings in azkaban.py

### ISSUE THREAD

**Issue by aguimaraesduarte** [globocom/azkaban-cli#40]
File `azkaban.py` is well documented with docstrings. However, some of the information in there is wrong with regards to the returns. Some are missing, some are incorrect... This issue is related to fixing all the docstrings so that they correspond to the expected outcome of each function call.

**Comment by Andy9822** [comment]
I believe I can take that issue!

**Comment by aguimaraesduarte** [comment]
@Andy9822 Awesome! Go ahead and thank you :)

**Comment by endersonmenezes** [comment]
@Andy9822 Do you need a help? If you need we can do it together and learn too ^^

**Comment by Andy9822** [comment]
Sure @endersonmenezes !
Any help is welcome and learning together too! 😁

**Comment by endersonmenezes** [comment]
I see ~23 functions ('def: ...'), you can make a PR, and We going making a commit for each docstring review, what do you think? Or... We can organize in this issue and make 2 PR.

Edit: Remembering that I'm a beginner, but I think I can do it ^^

**Comment by Andy9822** [comment]
@endersonmenezes 

Depending on your time and availability we can even try to do some part togther or even talk, as you said, you are a begginer and I may help you or at least exchange some ideas about this topic .
I'm kinda new in all of this open source contribution stuff so yeah, we can figure it out collaborating

**Comment by ggalves** [comment]
@endersonmenezes @Andy9822

Nice to see you two helping each other! If you guys need any help, let us know!

I hope to see your PR soon!

**Comment by endersonmenezes** [comment]
@Andy9822 We can talk on 22:30 ~ 1 AM (Brazilian Hour), We can split the work and try to study them, I'm programming to do this next week. We can post the explanations right here and then split everything into two PRs. What do you think? 

PS: It my bad, now that I saw that you are also Brazilian.

Edit2: Skype: enderson.menezes1 | Hangout: endersonster@gmail.com

Thx so much @ggalves!

**Comment by endersonmenezes** [comment]
I will start documenting the file, and as we can work together, I will document each function in a commit, so we may not repeat the functions.

**Comment by endersonmenezes** [comment]
@aguimaraesduarte 'urllib3' is not listed in requirements.txt, i can correct this too?

**Comment by aguimaraesduarte** [comment]
@endersonmenezes Sure
