### ISSUE TITLE
Add pre-commit to azkaban-cli

### ISSUE THREAD

**Issue by LeonardoFurtado** [globocom/azkaban-cli#51]
### Overview of the issue
Add pre-commit to the project, with black and flake8 set up.

### Motivation for or Use Case
I believe that standardizing the project code style is a good practice, so we can use [black](https://github.com/psf/black) and flake8, a useful tool for this purpose is [pre-commit](https://pre-commit.com/). I would like to configure this tool in the project as part of my contributions to hacktober fest.

**Comment by LeonardoFurtado** [comment]
if the issue is accepted, please assigne me

**Comment by ggalves** [comment]
@LeonardoFurtado go ahead :)
