### ISSUE TITLE
Use ReadTheDocs as documentation

### ISSUE THREAD

**Issue by dmvieira** [globocom/azkaban-cli#6]
Now ReadTheDocs is already [integrated](https://azkaban-cli.readthedocs.io/en/latest/), but not with documentation there.

There are already some documentation as docstring, but ReadTheDocs is not well integrated.

**Comment by Perkles** [comment]
Hi @dmvieira can I have this one?

**Comment by dmvieira** [comment]
Off course @Perkles! Do you need some help?

**Comment by Perkles** [comment]
#49 Closes this issue ?

**Comment by jackson541** [comment]
Hello, this issue has already been resolved in the [index.rst](https://github.com/globocom/azkaban-cli/blob/master/docs/index.rst) file?
