### ISSUE TITLE
Complement to CONTRIBUTING.md required

### ISSUE THREAD

**Issue by Perkles** [globocom/azkaban-cli#70]
The [CONTRIBUTING.md](https://github.com/globocom/azkaban-cli/blob/master/CONTRIBUTING.md#simple-process) divide the installation process into two steps:

 1 - pip install -e .
 2 - make test

It could misslead contributors. The comand ``pip install -e .`` install the dependences described in [requirements.txt](https://github.com/globocom/azkaban-cli/blob/master/requirements.txt) and under the [setup.py](https://github.com/globocom/azkaban-cli/blob/master/setup.py) ``install_requires`` atribute:

 - requests
 - click
 - beautifulsoup4

Ain't nothing wrong until here. But when you move to the next step (``make test``) the test suit doesn't run properly. The majority of the tests rely on the responses module but this module would not be installed by running ``pip install -e .``

The responses dependency is under setup.py > tests_require but ``pip install -e .`` won't reach that line. To properly run the ``make test`` I need to ``pip install -r requirements-dev.txt``.

Should this be described at CONTRIBUTING.md or there's some other way to install everything at once.

**Comment by LeonardoFurtado** [comment]
> Ain't nothing wrong until here. But when you move to the next step (`make test`) the test suit doesn't run properly. The majority of the tests rely on the responses module but this module would not be installed by running `pip install -e .`
> 
> The responses dependency is under setup.py > tests_require but `pip install -e .` won't reach that line. To properly run the `make test` I need to `pip install -r requirements-dev.txt`.


I think it's possible to setup.py install requirements and requirements-dev, I'll test it before doing a PR

**Comment by LeonardoFurtado** [comment]
So, what we can do here is to use `pip install -e .[test]` instead `pip install -e .`, this way we need to do:
`pip install -e .[test]`
`make test`
and all will run fine. But, looking at CONTRIBUTING.md I realize that we don't use `requirements-dev.txt` any moment in instalation step, but we require to contributors to use pre-commit that is in `requirements-dev.txt`. 
So, we need to delete `requirements-dev.txt` and put all this requirements in setup.py or we to continue using just `pip install -e .` and put `pip install -r requirements-dev.txt` as a step before `make test`

I would like @aguimaraesduarte  or @dmvieira give us an opinion about it before making my pull request.
If we remove `requirements-dev.txt`, setup.py will look like this:
```python
# -*- coding: utf-8 -*-

'''
Created on 2018-03-22

@author: gustavo.alves
'''
from setuptools import setup, find_packages
from azkaban_cli.__version__ import __version__

test_deps = [
    'responses==0.10.5',
    'twine',
    'sphinx',
    'pre-commit'
]
extras = {
    'test': test_deps,
}

setup(
    name='azkaban_cli',
    version=__version__,
    author = "Gustavo Alves",
    author_email = "gustavo.alves@corp.globo.com",
    description = ("Azkaban CLI"),
    packages=find_packages(exclude=['contrib', 'docs', 'tests']),
    py_modules=['azkaban_cli'],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Environment :: Console",
        "Intended Audience :: Developers",
        "Operating System :: POSIX",
        "Programming Language :: Python :: 3.7",
    ],
    install_requires=[
        'requests<2.30.0',
        'click<8.0',
        'beautifulsoup4<=4.7.1'
    ],
    tests_require=test_deps,
    extras_require=extras,
    entry_points='''
        [console_scripts]
        azkaban=azkaban_cli.azkaban_cli:cli
    ''',
)
```

**Comment by LeonardoFurtado** [comment]
I would like to know what do you think about it too @Perkles, particularly I prefer to use `requirements-dev`, sounds more 'clean' to me, but with `pip install -e .[test]` we do the same thing with a command.
![](https://media.giphy.com/media/JTUtO8ZZu4CdNmSOds/source.gif)

**Comment by Perkles** [comment]
Hey @LeonardoFurtado 

> I would like to know what do you think about it too @Perkles, particularly I prefer to use `requirements-dev`, sounds more 'clean' to me, but with `pip install -e .[test]` we do the same thing with a command.

I agree with you. This looks fine to me:

> ...or we to continue using just pip install -e . and put pip install -r requirements-dev.txt as a step before make test

**Comment by aguimaraesduarte** [comment]
Yeah, I would rather add the `pip install -r requirements-dev.txt` step before `make test`. It makes it more declarative and transparent in my opinion.

**Comment by Perkles** [comment]
Can we close this issue @aguimaraesduarte ?

**Comment by aguimaraesduarte** [comment]
@Perkles Yes. Thank you
